# Generated by Django 4.2.7 on 2023-11-03 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='date',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='high',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='low',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='volume',
        ),
        migrations.AddField(
            model_name='currency',
            name='abbr',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
            ],
        ),
    ]
