# Generated by Django 4.2.7 on 2023-11-03 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_remove_currency_close_remove_currency_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
