# Generated by Django 4.2.7 on 2023-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_history_dividends_history_stock_splits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='dividends',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='stock_splits',
            field=models.FloatField(default=0),
        ),
    ]
